### ISSUE TITLE
select.siemens_dishwasher_start_in option failure

### ISSUE THREAD

**Issue by Erwiiinst** [chris-mc1/homeconnect_local_hass#75]
### The problem

What is the time notation for the entity select.siemens_dishwasher_start_in?
By selecting the option also the option field is missing.

Time notation options seams not avialable. These should be somthing like 0:00 0:15 0:30 0:45 1:00 1:15 etc. or just seconds as in https://api-docs.home-connect.com/programs-and-options/#dishwasher_start-in-relative-option

### Diagnostics information

error: Option {{ wait_time_formatted }} is not valid for entity select.siemens_dishwasher_start_in, valid options are:

**Comment by Erwiiinst** [comment]
Time notation options seams not avialable. These should be somthing like 0:00 0:15 0:30 0:45 1:00 1:15 etc.

**Comment by chris-mc1** [comment]
Try version 1.0.4b5. The 'Start in' select has been removed, use 'homeconect_ws.start_program' Action instead.

**Comment by Erwiiinst** [comment]
The action for selecting the start time delay is missing when using the dishwasher equipment in an automation.

**Comment by chris-mc1** [comment]
Use the 'homeconnect_ws.start_program' Action to start with delay :

```yaml
action: homeconnect_ws.start_program
data:
  device_id: a309c8a40441de9e033523c5611d3c12
  start_in:
    hours: "{{ wait_hours_raw }}"
    minutes: 0
    seconds: 0
```
